/* ==========================================================================
   BONFIRE ADVENTURES — MASTER INVENTORY (DEMO DATA)
   --------------------------------------------------------------------------
   This is the single source of truth used by Packages, Find Your Trip,
   Budget, Destinations, Hotels & B&Bs, Deals, Compare and Global Search.
   ALL prices, availability, ratings and reviews below are clearly labelled
   SAMPLE DATA for wiring up the interface — replace with real Bonfire
   catalogue data / a live API before launch. Nothing here should be
   treated as a real price or booking guarantee.
   ========================================================================== */

const BONFIRE_DATA = (function () {

  // ---- Experience tags used across packages, hotels & the trip finder ----
  const EXPERIENCES = [
    "Beach", "Safari", "Adventure", "Romance", "Honeymoon", "Family",
    "Group", "Corporate", "Culture", "Nature", "Relaxation", "International"
  ];

  // ---- Explore Kenya categories -> destinations -------------------------
  // Each destination carries its own `images` array so Destination cards,
  // Destination pages, Explore Kenya, Search and Find Your Trip can all
  // reuse the same photos. `source: "uploaded"` = a real supplied photo of
  // that destination. `source: "fallback"` = no exact photo was supplied
  // yet, so an appropriate regional/experience photo is used temporarily —
  // swap it out the moment a real photo of that destination is supplied.
  const DESTINATIONS = [
    { id: "mombasa", name: "Mombasa", category: "Coast & Islands", region: "Coast", tagline: "Historic port city with island charm", experiences: ["Beach","Culture","Family"],
      images: [{ src: "assets/images/destinations/mombasa/mombasa-1.jpg", source: "placeholder" }] },
    { id: "diani", name: "Diani", category: "Coast & Islands", region: "Coast", tagline: "Powder-white sand and the reef beyond", experiences: ["Beach","Romance","Honeymoon","Relaxation"],
      images: [{ src: "assets/images/destinations/diani/diani-1.jpg", source: "placeholder" }] },
    { id: "watamu", name: "Watamu", category: "Coast & Islands", region: "Coast", tagline: "Marine park bays and dhow sails", experiences: ["Beach","Nature","Relaxation"],
      images: [{ src: "assets/images/destinations/watamu/watamu-1.jpg", source: "placeholder" }] },
    { id: "malindi", name: "Malindi", category: "Coast & Islands", region: "Coast", tagline: "Old town lanes meet ocean resorts", experiences: ["Beach","Culture","Family"],
      images: [{ src: "assets/images/destinations/malindi/malindi-1.jpg", source: "placeholder" }] },
    { id: "lamu", name: "Lamu", category: "Coast & Islands", region: "Coast", tagline: "Swahili archipelago, car-free streets", experiences: ["Culture","Romance","Relaxation"],
      images: [{ src: "assets/images/destinations/lamu/lamu-1.jpg", source: "placeholder" }] },
    { id: "maasai-mara", name: "Maasai Mara", category: "Wildlife & Safari", region: "Rift Valley", tagline: "The Great Migration's home ground", experiences: ["Safari","Nature","Honeymoon"],
      images: [{ src: "assets/images/destinations/maasai-mara/maasai-mara-1.jpg", source: "placeholder" }] },
    { id: "amboseli", name: "Amboseli", category: "Wildlife & Safari", region: "Rift Valley", tagline: "Elephant herds under Kilimanjaro", experiences: ["Safari","Nature","Family"],
      images: [{ src: "assets/images/destinations/amboseli/amboseli-1.jpg", source: "placeholder" }] },
    { id: "tsavo", name: "Tsavo", category: "Wildlife & Safari", region: "Coast", tagline: "Kenya's largest wilderness, red earth", experiences: ["Safari","Adventure","Nature"],
      images: [{ src: "assets/images/destinations/tsavo/tsavo-1.jpg", source: "placeholder" }] },
    { id: "samburu", name: "Samburu", category: "Wildlife & Safari", region: "Rift Valley", tagline: "Northern species and river-fed plains", experiences: ["Safari","Nature","Culture"],
      images: [{ src: "assets/images/destinations/samburu/samburu-1.jpg", source: "placeholder" }] },
    { id: "nakuru", name: "Nakuru", category: "Lakes & Nature", region: "Rift Valley", tagline: "Soda lake edged with flamingos", experiences: ["Nature","Safari","Family"],
      images: [{ src: "assets/images/destinations/nakuru/nakuru-1.jpg", source: "placeholder" }, { src: "assets/images/destinations/nakuru/nakuru-2.jpg", source: "placeholder" }] },
    { id: "naivasha", name: "Naivasha", category: "Lakes & Nature", region: "Rift Valley", tagline: "Freshwater lake, hippos and cycling trails", experiences: ["Nature","Adventure","Family"],
      images: [{ src: "assets/images/destinations/naivasha/naivasha-1.jpg", source: "placeholder" }, { src: "assets/images/destinations/naivasha/naivasha-2.jpg", source: "placeholder" }] },
    { id: "nairobi", name: "Nairobi", category: "City & Culture", region: "Nairobi", tagline: "Capital city safaris and skyline dining", experiences: ["Culture","Corporate","Family"],
      images: [{ src: "assets/images/destinations/nairobi/nairobi-1.jpg", source: "placeholder" }] },
    { id: "nanyuki", name: "Nanyuki", category: "Mountains & Highlands", region: "Central", tagline: "Equator town at Mount Kenya's foot", experiences: ["Adventure","Nature","Family"],
      images: [{ src: "assets/images/destinations/nanyuki/nanyuki-1.jpg", source: "placeholder" }] },
    { id: "mount-kenya", name: "Mount Kenya", category: "Mountains & Highlands", region: "Central", tagline: "Africa's second-highest summit", experiences: ["Adventure","Nature"],
      images: [{ src: "assets/images/destinations/mount-kenya/mount-kenya-1.jpg", source: "placeholder" }] },
    { id: "hells-gate", name: "Hell's Gate", category: "Adventure", region: "Rift Valley", tagline: "Cycle and climb through a gorge park", experiences: ["Adventure","Nature","Family"],
      images: [{ src: "assets/images/destinations/hells-gate/hells-gate-1.jpg", source: "placeholder" }] },
    { id: "lake-elementaita", name: "Lake Elementaita", category: "Lakes & Nature", region: "Rift Valley", tagline: "Quiet soda lake escape near Nakuru", experiences: ["Nature","Relaxation","Romance"],
      images: [{ src: "assets/images/destinations/lake-elementaita/lake-elementaita-1.jpg", source: "placeholder" }] },
    { id: "lake-victoria", name: "Lake Victoria", category: "Lakes & Nature", region: "Nyanza", tagline: "Africa's great lake at Kisumu's edge", experiences: ["Nature","Culture","Adventure"],
      images: [{ src: "assets/images/destinations/lake-victoria/lake-victoria-1.jpg", source: "placeholder" }] },
    { id: "kakamega", name: "Kakamega", category: "Lakes & Nature", region: "Western", tagline: "Kenya's last rainforest fragment", experiences: ["Nature","Adventure"],
      images: [{ src: "assets/images/destinations/kakamega/kakamega-1.jpg", source: "placeholder" }] },
    { id: "baringo", name: "Baringo", category: "Lakes & Nature", region: "Rift Valley", tagline: "Freshwater lake beneath dry cliffs", experiences: ["Nature","Adventure","Culture"],
      images: [{ src: "assets/images/destinations/baringo/baringo-1.jpg", source: "placeholder" }] },
    { id: "kilifi", name: "Kilifi", category: "Coast & Islands", region: "Coast", tagline: "Creek-side calm between Mombasa and Watamu", experiences: ["Beach","Relaxation","Nature"],
      images: [{ src: "assets/images/destinations/kilifi/kilifi-1.jpg", source: "placeholder" }] },
    { id: "eldoret", name: "Eldoret", category: "Mountains & Highlands", region: "Rift Valley", tagline: "Kenya's highland running capital", experiences: ["Adventure","Nature","Corporate"],
      images: [{ src: "assets/images/destinations/eldoret/eldoret-1.jpg", source: "placeholder" }] },
    { id: "kisumu", name: "Kisumu", category: "Lakes & Nature", region: "Nyanza", tagline: "Lakeside city on Lake Victoria's shore", experiences: ["Culture","Nature","Corporate"],
      images: [{ src: "assets/images/destinations/kisumu/kisumu-1.jpg", source: "placeholder" }] },
    { id: "naro-moru", name: "Naro Moru", category: "Mountains & Highlands", region: "Central", tagline: "Trailhead town on Mount Kenya's western flank", experiences: ["Adventure","Nature"],
      images: [{ src: "assets/images/destinations/naro-moru/naro-moru-1.jpg", source: "placeholder" }] }
  ];

  const DESTINATION_CATEGORIES = [
    "Coast & Islands", "Wildlife & Safari", "Lakes & Nature", "Mountains & Highlands",
    "Adventure", "City & Culture", "Romance", "Family", "Weekend Getaways"
  ];

  // ---- Hotels & B&Bs region hierarchy: Region -> Town -> Areas ----------
  const REGIONS = {
    "Coast": {
      towns: {
        "Mombasa": ["Nyali", "Bamburi", "Shanzu", "CBD"],
        "Diani / Ukunda": ["Diani Beach", "Ukunda", "Tiwi"],
        "Kilifi": ["Kilifi Town", "Mtwapa"],
        "Watamu": ["Watamu Village", "Turtle Bay"],
        "Malindi": ["Malindi Town", "Casuarina"],
        "Lamu": ["Lamu Old Town", "Shela"],
        "Taita/Taveta": ["Voi", "Wundanyi"]
      }
    },
    "Rift Valley": {
      towns: {
        "Nakuru": ["Nakuru Town", "Lake Nakuru"],
        "Naivasha": ["Naivasha Town", "Lake Naivasha"],
        "Eldoret": ["Eldoret Town"],
        "Kericho": ["Kericho Town"],
        "Baringo": ["Kampi ya Samaki"],
        "Narok": ["Narok Town", "Maasai Mara"],
        "Iten": ["Iten Town"]
      }
    },
    "Nairobi": {
      towns: {
        "Nairobi City": ["Westlands", "Kilimani", "Karen", "Lavington", "Kileleshwa", "CBD", "Gigiri", "Runda", "Parklands", "Upper Hill", "South C", "South B", "Lang'ata", "Embakasi"]
      }
    },
    "Central": {
      towns: { "Nyeri": ["Nyeri Town"], "Nanyuki": ["Nanyuki Town", "Ol Pejeta"], "Murang'a": ["Murang'a Town"], "Thika": ["Thika Town"], "Naro Moru": ["Naro Moru Town"] }
    },
    "Safari": {
      towns: { "Tsavo": ["Tsavo East", "Tsavo West"], "Amboseli": ["Amboseli Town"], "Samburu": ["Samburu Reserve"] }
    },
    "Western": {
      towns: { "Kakamega": ["Kakamega Town"], "Bungoma": ["Bungoma Town"], "Busia": ["Busia Town"] }
    },
    "Nyanza": {
      towns: { "Kisumu": ["Kisumu City", "Milimani", "Dunga"], "Homa Bay": ["Homa Bay Town"], "Migori": ["Migori Town"] }
    },
    "Eastern": {
      towns: { "Machakos": ["Machakos Town"], "Meru": ["Meru Town"], "Embu": ["Embu Town"], "Kitui": ["Kitui Town"] }
    },
    "North Eastern": {
      towns: { "Garissa": ["Garissa Town"], "Wajir": ["Wajir Town"], "Mandera": ["Mandera Town"] }
    }
  };

  const FEATURED_TOWNS = ["Nairobi City", "Nakuru", "Eldoret", "Kisumu", "Mombasa", "Diani / Ukunda"];

  // ---- Packages -----------------------------------------------------------
  const PACKAGES = [
    { id: "p1", name: "Diani Beach Escape", destinationId: "diani", region: "Coast", duration: "4 Days / 3 Nights", price: 32000, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Beach","Romance","Relaxation"], travellerType: ["Couples","Solo"], rating: 4.7, reviewCount: 128, image: "assets/images/packages/diani-beach-escape.jpg", desc: "Beachfront stay with reef snorkelling and a sunset dhow cruise.", inclusions: ["Return transfers","3 nights bed & breakfast","Sunset dhow cruise","Airport pickup"], exclusions: ["Flights","Travel insurance","Personal expenses"], accommodation: "3-star beach resort", transport: "Road transfer", meals: "Bed & breakfast" },
    { id: "p2", name: "Maasai Mara Migration Safari", destinationId: "maasai-mara", region: "Rift Valley", duration: "3 Days / 2 Nights", price: 68000, priceBasis: "per person", budgetBand: "40-70k", experiences: ["Safari","Nature","Honeymoon"], travellerType: ["Couples","Family","Group"], rating: 4.9, reviewCount: 214, image: "assets/images/packages/maasai-mara-migration-safari.jpg", desc: "Game drives across the plains during peak migration season.", inclusions: ["All game drives","Park fees","Full board","Road transfers"], exclusions: ["Balloon safari","Tips","Visa fees"], accommodation: "Tented safari camp", transport: "4x4 safari vehicle", meals: "Full board" },
    { id: "p3", name: "Amboseli Family Safari", destinationId: "amboseli", region: "Rift Valley", duration: "2 Days / 1 Night", price: 24500, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Safari","Family","Nature"], travellerType: ["Family"], rating: 4.5, reviewCount: 76, image: "assets/images/packages/amboseli-family-safari.jpg", desc: "Short escape to see elephant herds against Kilimanjaro's backdrop.", inclusions: ["Game drives","Park fees","Full board"], exclusions: ["Flights","Tips"], accommodation: "Lodge, family rooms", transport: "Road transfer", meals: "Full board" },
    { id: "p4", name: "Watamu Marine & Relax", destinationId: "watamu", region: "Coast", duration: "5 Days / 4 Nights", price: 45000, priceBasis: "per person", budgetBand: "40-70k", experiences: ["Beach","Relaxation","Nature"], travellerType: ["Couples","Solo","Family"], rating: 4.6, reviewCount: 95, image: "assets/images/packages/watamu-marine-relax.jpg", desc: "Marine park snorkelling, spa time and Gede ruins excursion.", inclusions: ["4 nights half board","Marine park entry","Gede ruins tour"], exclusions: ["Diving certification","Spa treatments"], accommodation: "Beachfront cottages", transport: "Road transfer", meals: "Half board" },
    { id: "p5", name: "Lamu Culture & Sail", destinationId: "lamu", region: "Coast", duration: "3 Days / 2 Nights", price: 39000, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Culture","Romance","Relaxation"], travellerType: ["Couples","Solo"], rating: 4.8, reviewCount: 61, image: "assets/images/packages/lamu-culture-sail.jpg", desc: "Old Town walking tour and a traditional dhow sunset sail.", inclusions: ["Return flights not included","2 nights B&B","Dhow sail","Guided old town walk"], exclusions: ["Flights to Lamu","Lunches"], accommodation: "Swahili boutique guesthouse", transport: "Boat & foot", meals: "Bed & breakfast" },
    { id: "p6", name: "Nakuru & Elementaita Weekend", destinationId: "nakuru", region: "Rift Valley", duration: "2 Days / 1 Night", price: 16500, priceBasis: "per person", budgetBand: "under-20k", experiences: ["Nature","Family","Safari"], travellerType: ["Family","Group"], rating: 4.4, reviewCount: 54, image: "assets/images/packages/nakuru-elementaita-weekend.jpg", desc: "Flamingo lake views and a relaxed rift valley weekend.", inclusions: ["Park fees","1 night full board","Road transfer"], exclusions: ["Bike hire"], accommodation: "Lakeside lodge", transport: "Road transfer", meals: "Full board" },
    { id: "p7", name: "Naivasha Adventure Weekend", destinationId: "naivasha", region: "Rift Valley", duration: "2 Days / 1 Night", price: 14000, priceBasis: "per person", budgetBand: "under-20k", experiences: ["Adventure","Nature","Family"], travellerType: ["Family","Group","Corporate"], rating: 4.3, reviewCount: 88, image: "assets/images/packages/naivasha-adventure-weekend.jpg", desc: "Cycling with giraffes at Hell's Gate and a boat ride on the lake.", inclusions: ["Cycling at Hell's Gate","Boat ride","1 night B&B"], exclusions: ["Bike damage waiver"], accommodation: "Lakeside camp", transport: "Road transfer", meals: "Bed & breakfast" },
    { id: "p8", name: "Nairobi City & Nature Break", destinationId: "nairobi", region: "Nairobi", duration: "1 Day", price: 9500, priceBasis: "per person", budgetBand: "under-20k", experiences: ["Culture","Corporate","Family"], travellerType: ["Solo","Corporate","Family"], rating: 4.2, reviewCount: 41, image: "assets/images/packages/nairobi-city-nature-break.jpg", desc: "Nairobi National Park game drive plus the Giraffe Centre.", inclusions: ["Park fees","Giraffe Centre entry","Guide"], exclusions: ["Lunch"], accommodation: "Day trip, no accommodation", transport: "Road transfer", meals: "None" },
    { id: "p9", name: "Mount Kenya Highlands Trek", destinationId: "mount-kenya", region: "Central", duration: "4 Days / 3 Nights", price: 58000, priceBasis: "per person", budgetBand: "40-70k", experiences: ["Adventure","Nature"], travellerType: ["Solo","Group"], rating: 4.7, reviewCount: 33, image: "assets/images/packages/mount-kenya-highlands-trek.jpg", desc: "Guided ascent toward Point Lenana with mountain-hut stays.", inclusions: ["Guide & porter","Park fees","Hut accommodation","Full board on trail"], exclusions: ["Personal trekking gear","Tips"], accommodation: "Mountain huts", transport: "On foot", meals: "Full board" },
    { id: "p10", name: "Samburu Northern Safari", destinationId: "samburu", region: "Rift Valley", duration: "3 Days / 2 Nights", price: 72000, priceBasis: "per person", budgetBand: "70-100k", experiences: ["Safari","Nature","Culture"], travellerType: ["Couples","Group"], rating: 4.8, reviewCount: 29, image: "assets/images/packages/samburu-northern-safari.jpg", desc: "Track reticulated giraffe and Grevy's zebra along the Ewaso Nyiro.", inclusions: ["Game drives","Park fees","Full board","Cultural village visit"], exclusions: ["Flights","Tips"], accommodation: "Riverside tented camp", transport: "4x4 safari vehicle", meals: "Full board" },
    { id: "p11", name: "Tsavo Wilderness Safari", destinationId: "tsavo", region: "Coast", duration: "3 Days / 2 Nights", price: 54000, priceBasis: "per person", budgetBand: "40-70k", experiences: ["Safari","Adventure","Nature"], travellerType: ["Family","Group"], rating: 4.5, reviewCount: 47, image: "assets/images/packages/tsavo-wilderness-safari.jpg", desc: "Red-earth plains, lava flows and the Mzima Springs hippo pools.", inclusions: ["Game drives","Park fees","Full board"], exclusions: ["Tips","Drinks"], accommodation: "Safari lodge", transport: "4x4 safari vehicle", meals: "Full board" },
    { id: "p12", name: "Kisumu & Lake Victoria Discovery", destinationId: "lake-victoria", region: "Nyanza", duration: "2 Days / 1 Night", price: 19500, priceBasis: "per person", budgetBand: "under-20k", experiences: ["Culture","Nature","Adventure"], travellerType: ["Solo","Group"], rating: 4.3, reviewCount: 22, image: "assets/images/packages/kisumu-lake-victoria-discovery.jpg", desc: "Lakeside city tour with a boat trip to Ndere Island.", inclusions: ["Boat trip","1 night B&B","City tour"], exclusions: ["Lunch"], accommodation: "Lakeside hotel", transport: "Road & boat", meals: "Bed & breakfast" },
    { id: "p13", name: "Kakamega Rainforest Walk", destinationId: "kakamega", region: "Western", duration: "2 Days / 1 Night", price: 17500, priceBasis: "per person", budgetBand: "under-20k", experiences: ["Nature","Adventure"], travellerType: ["Solo","Group"], rating: 4.4, reviewCount: 18, image: "assets/images/packages/kakamega-rainforest-walk.jpg", desc: "Guided walks through Kenya's last remnant rainforest.", inclusions: ["Forest guide","1 night B&B","Nature walks"], exclusions: ["Meals other than breakfast"], accommodation: "Forest guesthouse", transport: "Road transfer", meals: "Bed & breakfast" },
    { id: "p14", name: "Baringo Lakes & Cliffs", destinationId: "baringo", region: "Rift Valley", duration: "3 Days / 2 Nights", price: 27500, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Nature","Adventure","Culture"], travellerType: ["Group","Solo"], rating: 4.2, reviewCount: 15, image: "assets/images/packages/baringo-lakes-cliffs.jpg", desc: "Boat trips, hot springs and Njemps cultural encounters.", inclusions: ["Boat trips","2 nights full board","Cultural visit"], exclusions: ["Tips"], accommodation: "Lakeside lodge", transport: "Road & boat", meals: "Full board" },
    { id: "p15", name: "Corporate Retreat — Naivasha", destinationId: "naivasha", region: "Rift Valley", duration: "2 Days / 1 Night", price: 22000, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Corporate","Group"], travellerType: ["Corporate","Group"], rating: 4.5, reviewCount: 12, image: "assets/images/packages/corporate-retreat-naivasha.jpg", desc: "Conference facilities with team-building activities on the lake.", inclusions: ["Conference hall","1 night full board","Team-building session"], exclusions: ["AV equipment hire"], accommodation: "Resort with conference facilities", transport: "Road transfer", meals: "Full board" },
    { id: "p16", name: "Chama Group Getaway — Diani", destinationId: "diani", region: "Coast", duration: "3 Days / 2 Nights", price: 26000, priceBasis: "per person", budgetBand: "20-40k", experiences: ["Group","Beach","Family"], travellerType: ["Group"], rating: 4.6, reviewCount: 37, image: "assets/images/packages/chama-group-getaway-diani.jpg", desc: "Group beach villa stay with a bonfire night on the sand.", inclusions: ["2 nights self-catering villa","Bonfire night","Group transfers"], exclusions: ["Meals"], accommodation: "Beach villa, shared", transport: "Road transfer", meals: "Self-catering" },
    { id: "p17", name: "Honeymoon in Watamu", destinationId: "watamu", region: "Coast", duration: "5 Days / 4 Nights", price: 89000, priceBasis: "per person", budgetBand: "70-100k", experiences: ["Honeymoon","Romance","Beach"], travellerType: ["Couples"], rating: 4.9, reviewCount: 44, image: "assets/images/packages/honeymoon-in-watamu.jpg", desc: "Private beach dinners, couples spa and a snorkel excursion.", inclusions: ["4 nights half board","Couples spa session","Private beach dinner"], exclusions: ["Flights"], accommodation: "Boutique beach resort", transport: "Road transfer", meals: "Half board" },
    { id: "p18", name: "International — Zanzibar Add-On", destinationId: "diani", region: "International", duration: "5 Days / 4 Nights", price: 115000, priceBasis: "per person", budgetBand: "100k+", experiences: ["International","Beach","Romance"], travellerType: ["Couples","Group"], rating: 4.7, reviewCount: 26, image: "assets/images/packages/international-zanzibar-add-on.jpg", desc: "Cross-border beach extension to Zanzibar's Stone Town and spice tours.", inclusions: ["Return ferry/flight not included","4 nights B&B","Spice tour"], exclusions: ["International flights","Visa"], accommodation: "Beach resort", transport: "Regional flight/ferry", meals: "Bed & breakfast" }
  ];

  // ---- Hotels & B&Bs -------------------------------------------------------
  const HOTELS = [
    { id: "h-sarova-whitesands-beach-resort-spa", name: "Sarova Whitesands Beach Resort & Spa", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Resort", price: 24500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/sarova-whitesands-beach-resort-spa.jpg", images: ["assets/images/hotels/sarova-whitesands-beach-resort-spa.jpg"], description: "Resort in Mombasa with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-prideinn-paradise-beach-resort-spa-mombasa", name: "PrideInn Paradise Beach Resort & Spa Mombasa", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Resort", price: 23000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/prideinn-paradise-beach-resort-spa-mombasa.jpg", images: ["assets/images/hotels/prideinn-paradise-beach-resort-spa-mombasa.jpg"], description: "Resort in Mombasa with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-serena-beach-resort-spa", name: "Serena Beach Resort & Spa", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Resort", price: 22000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/serena-beach-resort-spa.jpg", images: ["assets/images/hotels/serena-beach-resort-spa.jpg"], description: "Resort in Mombasa with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-voyager-beach-resort", name: "Voyager Beach Resort", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Resort", price: 27300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/voyager-beach-resort.jpg", images: ["assets/images/hotels/voyager-beach-resort.jpg"], description: "Resort in Mombasa with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sentrim-castle-royal", name: "Sentrim Castle Royal", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Hotel", price: 6500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/sentrim-castle-royal.jpg", images: ["assets/images/hotels/sentrim-castle-royal.jpg"], description: "Hotel accommodation in Mombasa, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-mombasa-beach-hotel", name: "Mombasa Beach Hotel", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Hotel", price: 8000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/mombasa-beach-hotel.jpg", images: ["assets/images/hotels/mombasa-beach-hotel.jpg"], description: "Hotel accommodation in Mombasa, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-marigold-guest-house", name: "Marigold Guest House", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Guest House", price: 2500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Breakfast"], image: "assets/images/hotels/marigold-guest-house.jpg", images: ["assets/images/hotels/marigold-guest-house.jpg"], description: "Simple, well-located guest accommodation in Mombasa.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-hotel-englishpoint-mombasa", name: "Hotel Englishpoint Mombasa", region: "Coast", destination: "mombasa", town: "Mombasa", accommodationType: "Hotel", price: 14900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/hotel-englishpoint-mombasa.jpg", images: ["assets/images/hotels/hotel-englishpoint-mombasa.jpg"], description: "Hotel accommodation in Mombasa, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-prideinn-hotel-diani", name: "PrideInn Hotel Diani", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Hotel", price: 8000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/prideinn-hotel-diani.jpg", images: ["assets/images/hotels/prideinn-hotel-diani.jpg"], description: "Hotel accommodation in Diani, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-diani-reef-beach-resort-spa", name: "Diani Reef Beach Resort & Spa", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 18275, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/diani-reef-beach-resort-spa.jpg", images: ["assets/images/hotels/diani-reef-beach-resort-spa.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-safari-beach", name: "Safari Beach", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Hotel", price: 17416, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/safari-beach.jpg", images: ["assets/images/hotels/safari-beach.jpg"], description: "Hotel accommodation in Diani, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-diamonds-leisure-beach-golf-resort", name: "Diamonds Leisure Beach & Golf Resort", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 23000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/diamonds-leisure-beach-golf-resort.jpg", images: ["assets/images/hotels/diamonds-leisure-beach-golf-resort.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-baobab-beach-resort-spa", name: "Baobab Beach Resort & Spa", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 30000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/baobab-beach-resort-spa.jpg", images: ["assets/images/hotels/baobab-beach-resort-spa.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-southern-palms-beach-resort", name: "Southern Palms Beach Resort", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 34000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/southern-palms-beach-resort.jpg", images: ["assets/images/hotels/southern-palms-beach-resort.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-chale-island-resort", name: "Chale Island Resort", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 42000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/chale-island-resort.jpg", images: ["assets/images/hotels/chale-island-resort.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-nomad-beach-resort", name: "Nomad Beach Resort", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Resort", price: 46079, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/nomad-beach-resort.jpg", images: ["assets/images/hotels/nomad-beach-resort.jpg"], description: "Resort in Diani with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-swahili-beach", name: "Swahili Beach", region: "Coast", destination: "diani", town: "Diani", accommodationType: "Hotel", price: 60000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/swahili-beach.jpg", images: ["assets/images/hotels/swahili-beach.jpg"], description: "Hotel accommodation in Diani, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-casa-bella", name: "Casa Bella", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Hotel", price: 3000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/casa-bella-watamu.jpg", images: ["assets/images/hotels/casa-bella-watamu.jpg"], description: "Hotel accommodation in Watamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ocean-sports-resort", name: "Ocean Sports Resort", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Resort", price: 9070, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/ocean-sports-resort-watamu.jpg", images: ["assets/images/hotels/ocean-sports-resort-watamu.jpg"], description: "Resort in Watamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-jacaranda-beach-resort", name: "Jacaranda Beach Resort", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Resort", price: 9890, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/jacaranda-beach-resort-watamu.jpg", images: ["assets/images/hotels/jacaranda-beach-resort-watamu.jpg"], description: "Resort in Watamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-turtle-bay-beach-resort", name: "Turtle Bay Beach Resort", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Resort", price: 13100, priceCurrency: "KES", priceBasis: "per night", boardBasis: "Half Board", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/turtle-bay-beach-resort-watamu.jpg", images: ["assets/images/hotels/turtle-bay-beach-resort-watamu.jpg"], description: "Resort in Watamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-temple-point-resort", name: "Temple Point Resort", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Resort", price: 16600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/temple-point-resort-watamu.jpg", images: ["assets/images/hotels/temple-point-resort-watamu.jpg"], description: "Resort in Watamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-medina-palms", name: "Medina Palms", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Hotel", price: 18340, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/medina-palms-watamu.jpg", images: ["assets/images/hotels/medina-palms-watamu.jpg"], description: "Hotel accommodation in Watamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-hemingways-watamu", name: "Hemingways Watamu", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Hotel", price: 28900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/hemingways-watamu.jpg", images: ["assets/images/hotels/hemingways-watamu.jpg"], description: "Hotel accommodation in Watamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-rock-sea-resort", name: "Rock & Sea Resort", region: "Coast", destination: "watamu", town: "Watamu", accommodationType: "Resort", price: 30000, priceCurrency: "KES", priceBasis: "per night", boardBasis: "Half Board", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/rock-and-sea-resort-watamu.jpg", images: ["assets/images/hotels/rock-and-sea-resort-watamu.jpg"], description: "Resort in Watamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ozi-guest-house", name: "Ozi Guest House", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Guest House", price: 2500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Breakfast"], image: "assets/images/hotels/ozi-guest-house.jpg", images: ["assets/images/hotels/ozi-guest-house.jpg"], description: "Simple, well-located guest accommodation in Malindi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-scorpio-villas", name: "Scorpio Villas", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Villa", price: 3500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Family Friendly"], image: "assets/images/hotels/scorpio-villas-malindi.jpg", images: ["assets/images/hotels/scorpio-villas-malindi.jpg"], description: "Private villa-style accommodation in Malindi, suited to families or small groups.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-malindi-sea-fishing-club", name: "Malindi Sea Fishing Club", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Hotel", price: 7000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/malindi-sea-fishing-club.jpg", images: ["assets/images/hotels/malindi-sea-fishing-club.jpg"], description: "Hotel accommodation in Malindi, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sandies-tropical-village", name: "Sandies Tropical Village", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Villa", price: 9000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Family Friendly"], image: "assets/images/hotels/sandies-tropical-village.jpg", images: ["assets/images/hotels/sandies-tropical-village.jpg"], description: "Private villa-style accommodation in Malindi, suited to families or small groups.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-tropical-dream-hotel", name: "Tropical Dream Hotel", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Hotel", price: 12000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/tropical-dream-hotel-malindi.jpg", images: ["assets/images/hotels/tropical-dream-hotel-malindi.jpg"], description: "Hotel accommodation in Malindi, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-club-oasis-resort", name: "Club Oasis Resort", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Resort", price: 15000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/club-oasis-resort-malindi.jpg", images: ["assets/images/hotels/club-oasis-resort-malindi.jpg"], description: "Resort in Malindi with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-kasa-malindi", name: "The Kasa \u2013 Malindi", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Hotel", price: 27200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/the-kasa-malindi.jpg", images: ["assets/images/hotels/the-kasa-malindi.jpg"], description: "Hotel accommodation in Malindi, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ocean-beach-resort", name: "Ocean Beach Resort", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Resort", price: 13150, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/ocean-beach-resort-malindi.jpg", images: ["assets/images/hotels/ocean-beach-resort-malindi.jpg"], description: "Resort in Malindi with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-diamonds-dream-of-africa", name: "Diamonds Dream of Africa", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Hotel", price: 11000, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/diamonds-dream-of-africa.jpg", images: ["assets/images/hotels/diamonds-dream-of-africa.jpg"], description: "Hotel accommodation in Malindi, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-white-elephant-sea-lodge", name: "White Elephant Sea Lodge", region: "Coast", destination: "malindi", town: "Malindi", accommodationType: "Lodge", price: 8450, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/white-elephant-sea-lodge.jpg", images: ["assets/images/hotels/white-elephant-sea-lodge.jpg"], description: "Lodge-style stay in Malindi, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-baobab-sea-lodge", name: "Baobab Sea Lodge", region: "Coast", destination: "kilifi", town: "Kilifi", accommodationType: "Lodge", price: 9000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/baobab-sea-lodge.jpg", images: ["assets/images/hotels/baobab-sea-lodge.jpg"], description: "Lodge-style stay in Kilifi, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kilifi-bay-beach-resort", name: "Kilifi Bay Beach Resort", region: "Coast", destination: "kilifi", town: "Kilifi", accommodationType: "Resort", price: 10500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/kilifi-bay-beach-resort.jpg", images: ["assets/images/hotels/kilifi-bay-beach-resort.jpg"], description: "Resort in Kilifi with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-silver-palm-resort", name: "Silver Palm Resort", region: "Coast", destination: "kilifi", town: "Kilifi", accommodationType: "Resort", price: 16200, priceCurrency: "KES", priceBasis: "per night", boardBasis: "B&B", starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/silver-palm-resort.jpg", images: ["assets/images/hotels/silver-palm-resort.jpg"], description: "Resort in Kilifi with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-peacock-hotel-kilifi", name: "Peacock Hotel Kilifi", region: "Coast", destination: "kilifi", town: "Kilifi", accommodationType: "Hotel", price: 2100, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/peacock-hotel-kilifi.jpg", images: ["assets/images/hotels/peacock-hotel-kilifi.jpg"], description: "Hotel accommodation in Kilifi, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kijani-hotel", name: "Kijani Hotel", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Hotel", price: 11900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/kijani-hotel.jpg", images: ["assets/images/hotels/kijani-hotel.jpg"], description: "Hotel accommodation in Lamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-banana-house-wellness-centre", name: "Banana House & Wellness Centre", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Hotel", price: 7900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/banana-house-wellness-centre.jpg", images: ["assets/images/hotels/banana-house-wellness-centre.jpg"], description: "Hotel accommodation in Lamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-peponi-hotel", name: "Peponi Hotel", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Hotel", price: 11000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/peponi-hotel.jpg", images: ["assets/images/hotels/peponi-hotel.jpg"], description: "Hotel accommodation in Lamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-majlis-resort", name: "The Majlis Resort", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Resort", price: 16700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Beachfront", "Pool"], image: "assets/images/hotels/the-majlis-resort.jpg", images: ["assets/images/hotels/the-majlis-resort.jpg"], description: "Resort in Lamu with pool access and easy reach of the beach.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-manda-bay", name: "Manda Bay", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Hotel", price: 19000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/manda-bay.jpg", images: ["assets/images/hotels/manda-bay.jpg"], description: "Hotel accommodation in Lamu, Coast.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kizingo-eco-lodge", name: "Kizingo Eco Lodge", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Lodge", price: 18640, priceCurrency: "KES", priceBasis: "per person sharing", boardBasis: "Full Board", starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/kizingo-eco-lodge.jpg", images: ["assets/images/hotels/kizingo-eco-lodge.jpg"], description: "Lodge-style stay in Lamu, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-palm-house-shela", name: "Palm House, Shela", region: "Coast", destination: "lamu", town: "Lamu", accommodationType: "Villa", price: 60000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Family Friendly"], image: "assets/images/hotels/palm-house-shela.jpg", images: ["assets/images/hotels/palm-house-shela.jpg"], description: "Private villa-style accommodation in Lamu, suited to families or small groups.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-vicmark-hotel-nakuru", name: "Vicmark Hotel Nakuru", region: "Rift Valley", destination: "nakuru", town: "Nakuru", accommodationType: "Hotel", price: 5400, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/vicmark-hotel-nakuru.jpg", images: ["assets/images/hotels/vicmark-hotel-nakuru.jpg"], description: "Hotel accommodation in Nakuru, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-grand-winston-hotel", name: "Grand Winston Hotel", region: "Rift Valley", destination: "nakuru", town: "Nakuru", accommodationType: "Hotel", price: 7800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/grand-winston-hotel.jpg", images: ["assets/images/hotels/grand-winston-hotel.jpg"], description: "Hotel accommodation in Nakuru, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-midland-hotel", name: "The Midland Hotel", region: "Rift Valley", destination: "nakuru", town: "Nakuru", accommodationType: "Hotel", price: 10400, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/the-midland-hotel.jpg", images: ["assets/images/hotels/the-midland-hotel.jpg"], description: "Hotel accommodation in Nakuru, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-ole-ken-hotel", name: "The Ole-Ken Hotel", region: "Rift Valley", destination: "nakuru", town: "Nakuru", accommodationType: "Hotel", price: 13800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/the-ole-ken-hotel.jpg", images: ["assets/images/hotels/the-ole-ken-hotel.jpg"], description: "Hotel accommodation in Nakuru, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sawela-capella-resort", name: "Sawela Capella Resort", region: "Rift Valley", destination: "nakuru", town: "Nakuru", accommodationType: "Resort", price: 15300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Pool", "Spa"], image: "assets/images/hotels/sawela-capella-resort.jpg", images: ["assets/images/hotels/sawela-capella-resort.jpg"], description: "Resort in Nakuru with pool access and easy reach of the main attractions.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-lake-naivasha-sopa-resort", name: "Lake Naivasha Sopa Resort", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Resort", price: 15100, priceCurrency: "KES", priceBasis: "per person sharing", boardBasis: "Full Board", starRating: null, guestRating: null, amenities: ["Pool", "Spa"], image: "assets/images/hotels/lake-naivasha-sopa-resort.jpg", images: ["assets/images/hotels/lake-naivasha-sopa-resort.jpg"], description: "Resort in Naivasha with pool access and easy reach of the main attractions.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sawela-lodges", name: "Sawela Lodges", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Lodge", price: 12600, priceCurrency: "KES", priceBasis: "per person sharing", boardBasis: "Full Board", starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/sawela-lodges.jpg", images: ["assets/images/hotels/sawela-lodges.jpg"], description: "Lodge-style stay in Naivasha, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-lake-naivasha-simba-lodge", name: "Lake Naivasha Simba Lodge", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Lodge", price: 11700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/lake-naivasha-simba-lodge.jpg", images: ["assets/images/hotels/lake-naivasha-simba-lodge.jpg"], description: "Lodge-style stay in Naivasha, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-elmer-resort", name: "Elmer Resort", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Resort", price: 10200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Pool", "Spa"], image: "assets/images/hotels/elmer-resort.jpg", images: ["assets/images/hotels/elmer-resort.jpg"], description: "Resort in Naivasha with pool access and easy reach of the main attractions.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-lake-naivasha-kongoni-lodge", name: "Lake Naivasha Kongoni Lodge", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Lodge", price: 8900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/lake-naivasha-kongoni-lodge.jpg", images: ["assets/images/hotels/lake-naivasha-kongoni-lodge.jpg"], description: "Lodge-style stay in Naivasha, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-great-rift-valley-lodge", name: "Great Rift Valley Lodge", region: "Rift Valley", destination: "naivasha", town: "Naivasha", accommodationType: "Lodge", price: 11300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/great-rift-valley-lodge.jpg", images: ["assets/images/hotels/great-rift-valley-lodge.jpg"], description: "Lodge-style stay in Naivasha, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-melili-hotel", name: "Melili Hotel", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 6200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/melili-hotel.jpg", images: ["assets/images/hotels/melili-hotel.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-stardom-hotel", name: "Stardom Hotel", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 6600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/stardom-hotel.jpg", images: ["assets/images/hotels/stardom-hotel.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-marble-arch-hotel", name: "Marble Arch Hotel", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 8900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/marble-arch-hotel.jpg", images: ["assets/images/hotels/marble-arch-hotel.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-nairobi-safari-club", name: "Nairobi Safari Club", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 12700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/nairobi-safari-club.jpg", images: ["assets/images/hotels/nairobi-safari-club.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-golden-tulip-westlands", name: "Golden Tulip Westlands", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 16700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/golden-tulip-westlands.jpg", images: ["assets/images/hotels/golden-tulip-westlands.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-doubletree-by-hilton-nairobi-hurlingham", name: "DoubleTree by Hilton Nairobi Hurlingham", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 22100, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/doubletree-by-hilton-nairobi-hurlingham.jpg", images: ["assets/images/hotels/doubletree-by-hilton-nairobi-hurlingham.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-movenpick-hotel-residences", name: "Movenpick Hotel & Residences", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Apartment", price: 24200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/movenpick-hotel-residences.jpg", images: ["assets/images/hotels/movenpick-hotel-residences.jpg"], description: "Serviced apartments in Nairobi, suited to business and longer stays.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-safari-park-hotel-casino", name: "Safari Park Hotel & Casino", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 24500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/safari-park-hotel-casino.jpg", images: ["assets/images/hotels/safari-park-hotel-casino.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-raha-suites", name: "Raha Suites", region: "Nairobi", destination: "nairobi", town: "Nairobi", accommodationType: "Hotel", price: 9200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/raha-suites.jpg", images: ["assets/images/hotels/raha-suites.jpg"], description: "Hotel accommodation in Nairobi, Nairobi.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-comfy-inn-hotel-eldoret", name: "Comfy Inn Hotel Eldoret", region: "Rift Valley", destination: "eldoret", town: "Eldoret", accommodationType: "Hotel", price: 2500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/comfy-inn-hotel-eldoret.jpg", images: ["assets/images/hotels/comfy-inn-hotel-eldoret.jpg"], description: "Hotel accommodation in Eldoret, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-eka-hotel-eldoret", name: "Eka Hotel Eldoret", region: "Rift Valley", destination: "eldoret", town: "Eldoret", accommodationType: "Hotel", price: 12300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/eka-hotel-eldoret.jpg", images: ["assets/images/hotels/eka-hotel-eldoret.jpg"], description: "Hotel accommodation in Eldoret, Rift Valley.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-boma-inn-eldoret", name: "Boma Inn Eldoret", region: "Rift Valley", destination: "eldoret", town: "Eldoret", accommodationType: "Hotel", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/boma-inn-eldoret.jpg", images: ["assets/images/hotels/boma-inn-eldoret.jpg"], description: "Hotel accommodation in Eldoret, Rift Valley.", availabilityStatus: "Check Availability" },
    { id: "h-vijiji-hotel-conference", name: "VIJIJI Hotel & Conference", region: "Rift Valley", destination: "eldoret", town: "Eldoret", accommodationType: "Hotel", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/vijiji-hotel-conference.jpg", images: ["assets/images/hotels/vijiji-hotel-conference.jpg"], description: "Hotel accommodation in Eldoret, Rift Valley.", availabilityStatus: "Check Availability" },
    { id: "h-sai-inn-eldoret", name: "Sai Inn Eldoret", region: "Rift Valley", destination: "eldoret", town: "Eldoret", accommodationType: "Hotel", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Business"], image: "assets/images/hotels/sai-inn-eldoret.jpg", images: ["assets/images/hotels/sai-inn-eldoret.jpg"], description: "Hotel accommodation in Eldoret, Rift Valley.", availabilityStatus: "Check Availability" },
    { id: "h-shammah-hotel-kisumu", name: "Shammah Hotel Kisumu", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 3000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/shammah-hotel-kisumu.jpg", images: ["assets/images/hotels/shammah-hotel-kisumu.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-harry-s-kisumu-oasis", name: "Harry's Kisumu Oasis", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 4100, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/harry-s-kisumu-oasis.jpg", images: ["assets/images/hotels/harry-s-kisumu-oasis.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-pinecone-hotel", name: "Pinecone Hotel", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 5700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/pinecone-hotel.jpg", images: ["assets/images/hotels/pinecone-hotel.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-vip-luxury-lounge", name: "The VIP Luxury Lounge", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 4500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/the-vip-luxury-lounge.jpg", images: ["assets/images/hotels/the-vip-luxury-lounge.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-beachview-hotel", name: "BeachView Hotel", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 3200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/beachview-hotel.jpg", images: ["assets/images/hotels/beachview-hotel.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-imperial-hotel-express", name: "Imperial Hotel Express", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 10500, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/imperial-hotel-express.jpg", images: ["assets/images/hotels/imperial-hotel-express.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-vittoria-suites", name: "Vittoria Suites", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 13300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/vittoria-suites.jpg", images: ["assets/images/hotels/vittoria-suites.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-best-western-kisumu", name: "Best Western Kisumu", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 14600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/best-western-kisumu.jpg", images: ["assets/images/hotels/best-western-kisumu.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sovereign-hotel", name: "Sovereign Hotel", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 18800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/sovereign-hotel.jpg", images: ["assets/images/hotels/sovereign-hotel.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-acacia-premier-hotel", name: "Acacia Premier Hotel", region: "Nyanza", destination: "kisumu", town: "Kisumu", accommodationType: "Hotel", price: 16600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/acacia-premier-hotel.jpg", images: ["assets/images/hotels/acacia-premier-hotel.jpg"], description: "Hotel accommodation in Kisumu, Nyanza.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sentrim-lodge-tsavo-east", name: "Sentrim Lodge Tsavo East", region: "Safari", destination: "tsavo", town: "Tsavo East", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/sentrim-lodge-tsavo-east.jpg", images: ["assets/images/hotels/sentrim-lodge-tsavo-east.jpg"], description: "Lodge-style stay in Tsavo East, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-ashnil-aruba-lodge", name: "Ashnil Aruba Lodge", region: "Safari", destination: "tsavo", town: "Tsavo East", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/ashnil-aruba-lodge.jpg", images: ["assets/images/hotels/ashnil-aruba-lodge.jpg"], description: "Lodge-style stay in Tsavo East, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-voi-wildlife-lodge", name: "Voi Wildlife Lodge", region: "Safari", destination: "tsavo", town: "Tsavo East", accommodationType: "Lodge", price: 24600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/voi-wildlife-lodge.jpg", images: ["assets/images/hotels/voi-wildlife-lodge.jpg"], description: "Lodge-style stay in Tsavo East, set up for game viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-man-eaters-camp", name: "Man Eaters Camp", region: "Safari", destination: "tsavo", town: "Tsavo East", accommodationType: "Safari Camp", price: 25600, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/man-eaters-camp.jpg", images: ["assets/images/hotels/man-eaters-camp.jpg"], description: "Safari camp in Tsavo East, positioned for game drives and close wildlife viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kilaguni-serena-safari-lodge", name: "Kilaguni Serena Safari Lodge", region: "Safari", destination: "tsavo", town: "Tsavo West", accommodationType: "Lodge", price: 41300, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/kilaguni-serena-safari-lodge.jpg", images: ["assets/images/hotels/kilaguni-serena-safari-lodge.jpg"], description: "Lodge-style stay in Tsavo West, set up for game viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kiboko-camp", name: "Kiboko Camp", region: "Safari", destination: "tsavo", town: "Tsavo West", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/kiboko-camp.jpg", images: ["assets/images/hotels/kiboko-camp.jpg"], description: "Safari camp in Tsavo West, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-tsavo-lodge-voi", name: "Tsavo Lodge Voi", region: "Safari", destination: "tsavo", town: "Tsavo East", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/tsavo-lodge-voi.jpg", images: ["assets/images/hotels/tsavo-lodge-voi.jpg"], description: "Lodge-style stay in Tsavo East, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-loyk-tsavo-camp", name: "Loyk Tsavo Camp", region: "Safari", destination: "tsavo", town: "Tsavo West", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/loyk-tsavo-camp.jpg", images: ["assets/images/hotels/loyk-tsavo-camp.jpg"], description: "Safari camp in Tsavo West, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-amboseli-trails-cabin", name: "Amboseli Trails Cabin", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Hotel", price: 5000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/amboseli-trails-cabin.jpg", images: ["assets/images/hotels/amboseli-trails-cabin.jpg"], description: "Hotel accommodation in Amboseli, Safari.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-aa-lodge-amboseli", name: "AA Lodge Amboseli", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/aa-lodge-amboseli.jpg", images: ["assets/images/hotels/aa-lodge-amboseli.jpg"], description: "Lodge-style stay in Amboseli, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-sentrim-amboseli-lodge", name: "Sentrim Amboseli Lodge", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/sentrim-amboseli-lodge.jpg", images: ["assets/images/hotels/sentrim-amboseli-lodge.jpg"], description: "Lodge-style stay in Amboseli, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-kibo-safari-camp", name: "Kibo Safari Camp", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Safari Camp", price: 53000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/kibo-safari-camp.jpg", images: ["assets/images/hotels/kibo-safari-camp.jpg"], description: "Safari camp in Amboseli, positioned for game drives and close wildlife viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ol-tukai-lodge-amboseli", name: "Ol Tukai Lodge Amboseli", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Lodge", price: 66100, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/ol-tukai-lodge-amboseli.jpg", images: ["assets/images/hotels/ol-tukai-lodge-amboseli.jpg"], description: "Lodge-style stay in Amboseli, set up for game viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-amboseli-serena-safari-lodge", name: "Amboseli Serena Safari Lodge", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Lodge", price: 54800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/amboseli-serena-safari-lodge.jpg", images: ["assets/images/hotels/amboseli-serena-safari-lodge.jpg"], description: "Lodge-style stay in Amboseli, set up for game viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-elewana-tortilis-camp-amboseli", name: "Elewana Tortilis Camp Amboseli", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/elewana-tortilis-camp-amboseli.jpg", images: ["assets/images/hotels/elewana-tortilis-camp-amboseli.jpg"], description: "Safari camp in Amboseli, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-tawi-lodge", name: "Tawi Lodge", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/tawi-lodge.jpg", images: ["assets/images/hotels/tawi-lodge.jpg"], description: "Lodge-style stay in Amboseli, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-amboseli-discovery-camp", name: "Amboseli Discovery Camp", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/amboseli-discovery-camp.jpg", images: ["assets/images/hotels/amboseli-discovery-camp.jpg"], description: "Safari camp in Amboseli, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-amanya-camp", name: "Amanya Camp", region: "Safari", destination: "amboseli", town: "Amboseli", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/amanya-camp.jpg", images: ["assets/images/hotels/amanya-camp.jpg"], description: "Safari camp in Amboseli, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-samburu-sopa-lodge", name: "Samburu Sopa Lodge", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Lodge", price: 30200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/samburu-sopa-lodge.jpg", images: ["assets/images/hotels/samburu-sopa-lodge.jpg"], description: "Lodge-style stay in Samburu, set up for game viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-samburu-intrepids-tented-camp", name: "Samburu Intrepids Tented Camp", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Safari Camp", price: 40000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/samburu-intrepids-tented-camp.jpg", images: ["assets/images/hotels/samburu-intrepids-tented-camp.jpg"], description: "Safari camp in Samburu, positioned for game drives and close wildlife viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ashnil-samburu-camp", name: "Ashnil Samburu Camp", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Safari Camp", price: 44400, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/ashnil-samburu-camp.jpg", images: ["assets/images/hotels/ashnil-samburu-camp.jpg"], description: "Safari camp in Samburu, positioned for game drives and close wildlife viewing.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-samburu-simba-lodge", name: "Samburu Simba Lodge", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/samburu-simba-lodge.jpg", images: ["assets/images/hotels/samburu-simba-lodge.jpg"], description: "Lodge-style stay in Samburu, set up for game viewing.", availabilityStatus: "Check Availability" },
    { id: "h-saruni-samburu", name: "Saruni Samburu", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Hotel", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/saruni-samburu.jpg", images: ["assets/images/hotels/saruni-samburu.jpg"], description: "Hotel accommodation in Samburu, Safari.", availabilityStatus: "Check Availability" },
    { id: "h-elephant-watch-camp", name: "Elephant Watch Camp", region: "Safari", destination: "samburu", town: "Samburu", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Full Board", "Game Drives"], image: "assets/images/hotels/elephant-watch-camp.jpg", images: ["assets/images/hotels/elephant-watch-camp.jpg"], description: "Safari camp in Samburu, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-nanyuki-landmark-hotel", name: "Nanyuki Landmark Hotel", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 1800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/nanyuki-landmark-hotel.jpg", images: ["assets/images/hotels/nanyuki-landmark-hotel.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-farmhouse-inn-nanyuki", name: "The Farmhouse Inn, Nanyuki", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 4700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/the-farmhouse-inn-nanyuki.jpg", images: ["assets/images/hotels/the-farmhouse-inn-nanyuki.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-riverside-villas-nanyuki-hq-ya-marafiki", name: "Riverside Villas Nanyuki / HQ ya Marafiki", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Villa", price: 7000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Family Friendly"], image: "assets/images/hotels/riverside-villas-nanyuki-hq-ya-marafiki.jpg", images: ["assets/images/hotels/riverside-villas-nanyuki-hq-ya-marafiki.jpg"], description: "Private villa-style accommodation in Nanyuki, suited to families or small groups.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-glacier-hotel", name: "The Glacier Hotel", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 7900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/the-glacier-hotel.jpg", images: ["assets/images/hotels/the-glacier-hotel.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-kongoni-nanyuki", name: "Kongoni Nanyuki", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 8700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/kongoni-nanyuki.jpg", images: ["assets/images/hotels/kongoni-nanyuki.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-peaks-hotel-nanyuki", name: "Peaks Hotel Nanyuki", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 10700, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/peaks-hotel-nanyuki.jpg", images: ["assets/images/hotels/peaks-hotel-nanyuki.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-the-sportsman-s-arms-hotel", name: "The Sportsman's Arms Hotel", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 11000, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/the-sportsman-s-arms-hotel.jpg", images: ["assets/images/hotels/the-sportsman-s-arms-hotel.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-falcon-heights-hotel-nanyuki", name: "Falcon Heights Hotel Nanyuki", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 14100, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/falcon-heights-hotel-nanyuki.jpg", images: ["assets/images/hotels/falcon-heights-hotel-nanyuki.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-le-rustique-hotel", name: "Le Rustique Hotel", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 14800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/le-rustique-hotel.jpg", images: ["assets/images/hotels/le-rustique-hotel.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-esiankiki-resort-spa", name: "Esiankiki Resort & Spa", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Resort", price: 7900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Pool", "Spa"], image: "assets/images/hotels/esiankiki-resort-spa.jpg", images: ["assets/images/hotels/esiankiki-resort-spa.jpg"], description: "Resort in Nanyuki with pool access and easy reach of the main attractions.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-sweetwaters-serena-camp", name: "Sweetwaters Serena Camp", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Safari Camp", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/sweetwaters-serena-camp.jpg", images: ["assets/images/hotels/sweetwaters-serena-camp.jpg"], description: "Safari camp in Nanyuki, positioned for game drives and close wildlife viewing.", availabilityStatus: "Check Availability" },
    { id: "h-fairmont-mount-kenya-safari-club", name: "Fairmont Mount Kenya Safari Club", region: "Central", destination: "nanyuki", town: "Nanyuki", accommodationType: "Hotel", price: 56800, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/fairmont-mount-kenya-safari-club.jpg", images: ["assets/images/hotels/fairmont-mount-kenya-safari-club.jpg"], description: "Hotel accommodation in Nanyuki, Central.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-naro-moru-river-lodge", name: "Naro Moru River Lodge", region: "Central", destination: "naro-moru", town: "Naro Moru", accommodationType: "Lodge", price: 10200, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/naro-moru-river-lodge.jpg", images: ["assets/images/hotels/naro-moru-river-lodge.jpg"], description: "Lodge-style stay in Naro Moru, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-podocarpus-cottages", name: "Podocarpus Cottages", region: "Central", destination: "naro-moru", town: "Naro Moru", accommodationType: "Lodge", price: 2900, priceCurrency: "KES", priceBasis: "per night", boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/podocarpus-cottages.jpg", images: ["assets/images/hotels/podocarpus-cottages.jpg"], description: "Lodge-style stay in Naro Moru, set up for a relaxed nature-focused break.", availabilityStatus: "Indicative pricing \u2014 contact to confirm" },
    { id: "h-ole-lekurruki-naromoru-cabins", name: "Ole-lekurruki Naromoru Cabins", region: "Central", destination: "naro-moru", town: "Naro Moru", accommodationType: "Lodge", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Nature", "Full Board"], image: "assets/images/hotels/ole-lekurruki-naromoru-cabins.jpg", images: ["assets/images/hotels/ole-lekurruki-naromoru-cabins.jpg"], description: "Lodge-style stay in Naro Moru, set up for a relaxed nature-focused break.", availabilityStatus: "Check Availability" },
    { id: "h-anka-resort", name: "Anka Resort", region: "Central", destination: "naro-moru", town: "Naro Moru", accommodationType: "Resort", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Pool", "Spa"], image: "assets/images/hotels/anka-resort.jpg", images: ["assets/images/hotels/anka-resort.jpg"], description: "Resort in Naro Moru with pool access and easy reach of the main attractions.", availabilityStatus: "Check Availability" },
    { id: "h-idan-barn-suites-caf", name: "Idan Barn Suites & Caf\u00e9", region: "Central", destination: "naro-moru", town: "Naro Moru", accommodationType: "Hotel", price: null, priceCurrency: "KES", priceBasis: null, boardBasis: null, starRating: null, guestRating: null, amenities: ["Wi-Fi", "Restaurant"], image: "assets/images/hotels/idan-barn-suites-caf.jpg", images: ["assets/images/hotels/idan-barn-suites-caf.jpg"], description: "Hotel accommodation in Naro Moru, Central.", availabilityStatus: "Check Availability" },
  ];

  // ---- Deals (each deal expires — expired deals must not show as active) --
  const DEALS = [
    { id: "d1", title: "Diani Beach Escape — Early Bird", category: "Hot Deals", packageId: "p1", originalPrice: 38000, dealPrice: 32000, validUntil: "2026-09-30", travelPeriod: "Sep – Oct 2026", inclusions: ["3 nights B&B","Dhow cruise","Transfers"] },
    { id: "d2", title: "Maasai Mara Weekend Flash Sale", category: "Last-Minute", packageId: "p2", originalPrice: 79000, dealPrice: 68000, validUntil: "2026-08-24", travelPeriod: "Aug 2026 only", inclusions: ["Game drives","Full board","Transfers"] },
    { id: "d3", title: "Nakuru Weekender", category: "Weekend", packageId: "p6", originalPrice: 19500, dealPrice: 16500, validUntil: "2026-12-20", travelPeriod: "Any weekend, 2026", inclusions: ["1 night full board","Park fees"] },
    { id: "d4", title: "Festive Season — Watamu Honeymoon", category: "Seasonal", packageId: "p17", originalPrice: 102000, dealPrice: 89000, validUntil: "2026-12-15", travelPeriod: "Dec 2026", inclusions: ["4 nights half board","Couples spa"] },
    { id: "d5", title: "Holiday Family Amboseli", category: "Holiday", packageId: "p3", originalPrice: 29500, dealPrice: 24500, validUntil: "2026-09-05", travelPeriod: "School holidays 2026", inclusions: ["Game drives","Full board"] },
    { id: "d6", title: "Nairobi Boutique Hotel Getaway", category: "Hotel & B&B", hotelId: "h-golden-tulip-westlands", originalPrice: 19500, dealPrice: 16700, validUntil: "2026-10-31", travelPeriod: "Sep – Oct 2026", inclusions: ["B&B rate","Late checkout"] },
    { id: "d7", title: "SGR + Diani Combo (Advisor Assisted)", category: "SGR", packageId: "p1", originalPrice: 41000, dealPrice: 35500, validUntil: "2026-11-30", travelPeriod: "Sep – Nov 2026", inclusions: ["SGR ticket coordination","3 nights B&B"] },
    { id: "d8", title: "Family Naivasha Adventure", category: "Family", packageId: "p7", originalPrice: 17000, dealPrice: 14000, validUntil: "2026-09-15", travelPeriod: "Aug – Sep 2026", inclusions: ["Cycling","Boat ride","B&B"] },
    { id: "d9", title: "Group Diani Bonfire Weekend", category: "Group", packageId: "p16", originalPrice: 31000, dealPrice: 26000, validUntil: "2026-10-10", travelPeriod: "Sep – Oct 2026", inclusions: ["Villa stay","Bonfire night"] },
    { id: "d10", title: "Corporate Naivasha Retreat", category: "Corporate", packageId: "p15", originalPrice: 26500, dealPrice: 22000, validUntil: "2026-09-25", travelPeriod: "Weekdays, Sep 2026", inclusions: ["Conference hall","Full board"] },
    { id: "d11", title: "Zanzibar Extension Offer", category: "International", packageId: "p18", originalPrice: 132000, dealPrice: 115000, validUntil: "2026-11-01", travelPeriod: "Sep – Nov 2026", inclusions: ["Spice tour","4 nights B&B"] },
    { id: "d12", title: "Winter Sale — Nairobi Day Trip", category: "Kenya Deals", packageId: "p8", originalPrice: 12000, dealPrice: 9500, validUntil: "2026-08-20", travelPeriod: "Aug 2026", inclusions: ["Park fees","Giraffe Centre"] },
    // Intentionally expired demo deal — used to test the "expired" empty state
    { id: "d13", title: "Easter Diani Splash (Expired)", category: "Seasonal", packageId: "p1", originalPrice: 30000, dealPrice: 24000, validUntil: "2026-04-01", travelPeriod: "Mar – Apr 2026", inclusions: ["3 nights B&B"] }
  ];

  // ---- Reviews (sample, structured for later replacement) -----------------
  const REVIEWS = [
    { id: "r1", name: "Achieng O.", rating: 5, text: "Our Mara trip was seamless from booking to the last game drive. The advisor answered every WhatsApp message fast.", context: "Maasai Mara Migration Safari" },
    { id: "r2", name: "Brian K.", rating: 5, text: "Diani villa was exactly as pictured and the bonfire night with our chama was the highlight of the year.", context: "Chama Group Getaway — Diani" },
    { id: "r3", name: "Faith M.", rating: 4, text: "Great value weekend in Naivasha, cycling with the giraffes was unforgettable for the kids.", context: "Naivasha Adventure Weekend" },
    { id: "r4", name: "Peter N.", rating: 5, text: "Lamu felt like stepping into another century. Loved the dhow sunset sail and the old town walk.", context: "Lamu Culture & Sail" },
    { id: "r5", name: "Grace W.", rating: 5, text: "Booked our honeymoon through Bonfire and the private beach dinner in Watamu was worth every shilling.", context: "Honeymoon in Watamu" }
  ];

  const BUDGET_BANDS = [
    { id: "under-20k", label: "Under KSh 20,000", min: 0, max: 20000 },
    { id: "20-40k", label: "KSh 20,000 – 40,000", min: 20000, max: 40000 },
    { id: "40-70k", label: "KSh 40,000 – 70,000", min: 40000, max: 70000 },
    { id: "70-100k", label: "KSh 70,000 – 100,000", min: 70000, max: 100000 },
    { id: "100k+", label: "KSh 100,000+", min: 100000, max: Infinity }
  ];

  function formatKES(amount) {
    return "KSh " + Number(amount).toLocaleString("en-KE");
  }

  function isDealActive(deal, today) {
    today = today || new Date();
    return new Date(deal.validUntil) >= today;
  }

  function getActiveDeals() {
    const today = new Date();
    return DEALS.filter(function (d) { return isDealActive(d, today); });
  }

  function getPackageById(id) { return PACKAGES.find(function (p) { return p.id === id; }); }
  function getHotelById(id) { return HOTELS.find(function (h) { return h.id === id; }); }
  function getDestinationById(id) { return DESTINATIONS.find(function (d) { return d.id === id; }); }

  return {
    EXPERIENCES: EXPERIENCES,
    DESTINATIONS: DESTINATIONS,
    DESTINATION_CATEGORIES: DESTINATION_CATEGORIES,
    REGIONS: REGIONS,
    FEATURED_TOWNS: FEATURED_TOWNS,
    PACKAGES: PACKAGES,
    HOTELS: HOTELS,
    DEALS: DEALS,
    REVIEWS: REVIEWS,
    BUDGET_BANDS: BUDGET_BANDS,
    formatKES: formatKES,
    isDealActive: isDealActive,
    getActiveDeals: getActiveDeals,
    getPackageById: getPackageById,
    getHotelById: getHotelById,
    getDestinationById: getDestinationById
  };
})();
